Portfolio feature one section
sheldonwafula/The-portfolio pull request #1
Opened 2023-04-26 13:42 UTC by sheldonwafula

In this pull request:
I have created HTML and CSS files.
I have added a descriptive readme file.
I have corrected the linter errors.

2023-04-26 14:36 UTC, christianbiring1 requested changes
Hi @sheldonwafula , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/234609918-44134c6b-f7eb-4ab0-a312-ad8bea0cc1ad.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Good looking UI :+1:  
- [ ] Use of semantic tags :art: :1st_place_medal: 

## Required Changes ♻️
- [ ] You may consider giving your PR a descriptive `title` telling what changes have been introduced.
Hint: `Set up and mobile first and mobile first` would sound more descriptive than `Portfolio feature one section.`
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 14:36 UTC, christianbiring1 commented on README.md
> +  </ul>
- [ ] Kinldy you may consider adding CSS as well among the tech stacks

2023-04-26 14:36 UTC, christianbiring1 commented on README.md
> +- **[Heading]**
If you do not have any key features to highlight, you may consider deleting the section

2023-04-26 14:36 UTC, christianbiring1 commented on README.md
> +
- [ ] Kindly you may consider proving the command to get started with the copy of the project locally and how to run it as well.
```sh
git clone repo_link
cd repo_directory
open the project in a  code. Editor
```

2023-04-26 14:36 UTC, christianbiring1 commented on README.md
> +
- [ ] YOu may consider saying one needs to have nodeJS installed in their computer, version control Git, and a code editor to run the project.

2023-04-26 14:36 UTC, christianbiring1 commented on README.md
> +
- [ ] Since you do not yet have any tests to run on your project or as the project is not yet deployed, you may consider saying Not applicable or Not applicable.

2023-04-27 14:49 UTC, ShadyShawkat approved these changes
## Hi @sheldonwafula, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 14:53 UTC, merged