Portfolio mobile contact section
sheldonwafula/The-portfolio pull request #3
Opened 2023-05-02 13:29 UTC by sheldonwafula

In this pull request:
I have added a contact form.
I have added a descriptive readme file.
I have corrected linter errors.

2023-05-02 13:58 UTC, levy002 requested changes
## Hello @sheldonwafula   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 
- Well-detailed PR :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 13:58 UTC, levy002 commented on style.css
> +  }
- [ ] Kindly make sure to center the form inputs in order to the provided Figma design.

    - ### YOUR DESIGN
    
     ![image](https://user-images.githubusercontent.com/87197412/235687331-ead1c649-7283-4fc3-b79a-c1b97bdecddf.png)

    - ### FIGMA DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235687486-0dcebfd5-9237-4b2d-bf57-422ef9591bf5.png)

2023-05-02 13:58 UTC, levy002 commented on index.html
> +        </div>
- [ ] Kindly make sure to close the `<div>` container with `contact-section` class, you forgot to add the closing `</div>`. Kindly fix that.

2023-05-02 13:58 UTC, levy002 commented on index.html
> +        </div>
- [OPTIONAL] It is not necessary to add this black horizontal line, because the reason for this line was to show that it is a mobile design only. You remove it.

2023-05-02 16:00 UTC, emmiiorji requested changes
Hi @sheldonwafula and Team, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- Good design
- Project is well documented in readme


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 16:00 UTC, emmiiorji commented on style.css
> +
Well done for performing the alignment as requested by the previous reviewer. You seem to now have much more margin than on the design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/235719740-9272fee7-23fa-420a-828a-236887b68e95.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/235720138-f0219066-47d1-467b-9322-ee4acbaadd73.png)

2023-05-03 02:59 UTC, Efiamotu-1 approved these changes
Hi @sheldonwafula , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 02:59 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [x] please kindly use descriptive words as placeholders in your contact forms so that users of your portfolio can be exactly sure of what to input in a giving field. see the design from one of the other templates below as example reference :+1: 

![exam](https://user-images.githubusercontent.com/89055502/235815016-e853e953-370e-4816-9013-08d059ea1c37.png)

2023-05-03 02:59 UTC, Efiamotu-1 commented on index.html
>               </div>
- [ ] kindly fix this design flaw with your toolbar section in your project as shown below it is important you do this before merging your project. :+1: 
![new-e](https://user-images.githubusercontent.com/89055502/235824906-747e3773-b933-41e0-b156-d0950fae4067.png)

2023-05-03 15:58 UTC, merged